### ISSUE TITLE
No values shown

### ISSUE THREAD

**Issue by gertjana** [jdbranham/grafana-diagram#82]
Hi, after updating to grafana 4.6.1 and grafana-diagram 1.4.4 I don't see the values below the graphs anymore and the panel shows an error "Cannot read property '0' of undefined"
any clue what's causing this?

Inspector:
```
TypeError: Cannot read property '0' of undefined
    at Object.a.stringToJsRegex (http://bla/public/build/app.8849fc3d424a44caa6fc.js:1:3566)
    at DiagramCtrl.applyOverrides (http://bla/public/plugins/jdbranham-diagram-panel/diagramControl.js:636:33)
    at DiagramCtrl.setValues (http://bla/public/plugins/jdbranham-diagram-panel/diagramControl.js:501:47)
    at DiagramCtrl.onDataReceived (http://bla/public/plugins/jdbranham-diagram-panel/diagramControl.js:216:18)
    at o.emit (http://bla/public/build/vendor.2305a8e1d478628b1297.js:15:520749)
    at t.emit (http://bla/public/build/app.8849fc3d424a44caa6fc.js:1:29207)
    at DiagramCtrl.e.handleQueryResult (http://bla/public/build/0.7d03bf00820ec00459ae.js:7:19860)
    at u (http://bla/public/build/vendor.2305a8e1d478628b1297.js:43:68722)
    at http://bla/public/build/vendor.2305a8e1d478628b1297.js:43:69127
    at f.$digest (http://bla/public/build/vendor.2305a8e1d478628b1297.js:43:74824)
```
I've included the panel json, with sensitive information replaced

```
{
  "colors": [
    "rgb(147, 177, 210)",
    "rgb(102, 117, 208)"
  ],
  "composites": [],
  "content": "graph LR\nA((one)) --> B[something]\nB --> D(two)\nB --> E(three)\nB --> F(four)\nB --> G(five)",
  "datasource": "Graphite",
  "decimals": 0,
  "editable": true,
  "error": false,
  "format": "none",
  "graphId": "diagram_10",
  "id": 10,
  "init": {
    "arrowMarkerAbsolute": true,
    "cloneCssStyles": false,
    "flowchart": {
      "htmlLabels": true,
      "useMaxWidth": true
    },
    "gantt": {
      "barGap": 4,
      "barHeight": 20,
      "fontFamily": "\"Open-Sans\", \"sans-serif\"",
      "fontSize": 11,
      "gridLineStartPadding": 35,
      "leftPadding": 75,
      "numberSectionStyles": 3,
      "titleTopMargin": 25,
      "topPadding": 50
    },
    "logLevel": 3,
    "sequenceDiagram": {
      "actorMargin": 50,
      "bottomMarginAdj": 1,
      "boxMargin": 10,
      "boxTextMargin": 5,
      "diagramMarginX": 50,
      "diagramMarginY": 10,
      "height": 65,
      "messageMargin": 35,
      "mirrorActors": true,
      "noteMargin": 10,
      "useMaxWidth": true,
      "width": 150
    },
    "startOnLoad": false
  },
  "legend": {
    "avg": false,
    "current": true,
    "gradient": {
      "enabled": false,
      "show": true
    },
    "max": false,
    "min": false,
    "show": false,
    "total": true
  },
  "links": [],
  "mappingType": 1,
  "maxDataPoints": 100,
  "maxWidth": false,
  "mermaidServiceUrl": "",
  "metricCharacterReplacements": [],
  "mode": "url",
  "nullPointMode": "connected",
  "seriesOverrides": [
    {}
  ],
  "span": 3,
  "targets": [
    {
      "refId": "A",
      "target": "aliasByMetric(stats.gauges.one)",
      "textEditor": false
    },
    {
      "refId": "B",
      "target": "alias(stats.gauges.two, 'two')",
      "textEditor": false
    },
    {
      "refId": "C",
      "target": "alias(stats.gauges.three, 'three')",
      "textEditor": false
    },
    {
      "refId": "D",
      "target": "alias(stats.gauges.four, 'four')",
      "textEditor": false
    },
    {
      "refId": "E",
      "target": "alias(stats.gauges.five, 'five')",
      "textEditor": false
    },
    {
      "refId": "F",
      "target": "alias(sumSeries(stats.gauges.*), 'total')",
      "textEditor": false
    }
  ],
  "thresholds": "10000",
  "title": "",
  "type": "jdbranham-diagram-panel",
  "valueMaps": [
    {
      "op": "=",
      "text": "N/A",
      "value": "null"
    }
  ],
  "valueName": "current",
  "valueOptions": [
    "avg",
    "min",
    "max",
    "total",
    "current"
  ]
}
```

**Comment by gertjana** [comment]
nevermind, issue between chair and keyboard
